//! Emits the embedded-asset table consumed by `src/assets.rs`.
//!
//! Walks the two asset trees the binary ships — the frontend in `web/dist`
//! and the vendored icon theme in `res/icons` — and writes a
//! `$OUT_DIR/assets.rs` holding one `include_bytes!` entry per file, keyed by
//! its forward-slash path relative to the project root. `rerun-if-changed` is
//! emitted for the directories themselves, so adding or editing a file inside
//! either tree rebuilds without touching anything else.

use std::path::{Path, PathBuf};

/// Asset trees to embed, in the order they appear in the generated table.
const ROOTS: &[&str] = &["web/dist", "res/icons"];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").unwrap());
    let out_dir = PathBuf::from(std::env::var("OUT_DIR").unwrap());

    let mut entries: Vec<(String, String)> = Vec::new();
    for root in ROOTS {
        let dir = manifest.join(root);
        // Directory-level: cargo cannot diff directory contents on its own, so
        // a change to any file inside invalidates the build script.
        println!("cargo:rerun-if-changed={}", dir.display());
        collect(&manifest, &dir, &mut entries);
    }
    entries.sort();

    let mut src = String::from("// @generated by build.rs — do not edit.\n");
    src.push_str("pub static ASSETS: &[(&str, &[u8])] = &[\n");
    for (key, include) in &entries {
        src.push_str(&format!("    ({key:?}, include_bytes!({include:?})),\n"));
    }
    src.push_str("];\n");

    std::fs::write(out_dir.join("assets.rs"), src).unwrap_or_else(|e| {
        panic!(
            "failed to write {}: {e}",
            out_dir.join("assets.rs").display()
        )
    });
}

/// Collects every file under `dir`, keyed by its forward-slash path relative
/// to `base` (the manifest directory). The `include_bytes!` path is absolute
/// because that macro resolves relative paths against the generated file's own
/// directory in `OUT_DIR`, not the manifest.
fn collect(base: &Path, dir: &Path, entries: &mut Vec<(String, String)>) {
    let Ok(read) = std::fs::read_dir(dir) else {
        panic!("asset directory missing: {}", dir.display());
    };
    for item in read.flatten() {
        let path = item.path();
        if path.is_dir() {
            collect(base, &path, entries);
            continue;
        }
        let rel = path.strip_prefix(base).unwrap_or(&path);
        let key = rel.to_string_lossy().replace('\\', "/");
        entries.push((key, path.to_string_lossy().replace('\\', "/")));
    }
}
